### ISSUE TITLE
Uninitialized variable in scripts/zef_KalmanDemo

### ISSUE THREAD

**Issue by SeSodesa** [sampsapursiainen/zeffiro_interface#146]
I noticed this while working on #141, but `project_struct` in the script `scripts/zef_KalmanDemo` is currently not initialized properly:

    % Create project
    project_struct = zef_

I guess `zef_` should be followed by something, but I don't know what. Could somebody look into this? Latest edit was by Sampsa, so I am adding him as an assignee as well.

**Comment by sampsapursiainen** [comment]
Corrected. My mistake from the weekend.

**Comment by SeSodesa** [comment]
Fixed by 47adc81e27d7378c00d0eda55182aeb6e66b1af1?
