### ISSUE TITLE
zef_transfer_matrix broken by missing variable definition

### ISSUE THREAD

**Issue by SeSodesa** [sampsapursiainen/zeffiro_interface#147]
When trying to run the EEG routine, the following error is thrown in the CPU branch of `zef_transfer_matrix`:

    >> zef_eeg_lead_field
    Unrecognized function or variable 'n_parallel'.

    Error in zef_transfer_matrix (line 243)
                parpool(n_parallel);

    Error in zef_lead_field_eeg_fem (line 207)
    [T, Schur_complement, ~] = zef_transfer_matrix(...

    Error in zef_lead_field_matrix (line 158)
        [zef.L, zef.source_positions, zef.source_directions] = zef_lead_field_eeg_fem( ...

    Error in zef_eeg_lead_field (line 13)
    zef = zef_lead_field_matrix(zef);

I'm not sure where `n_parallel` is supposed to come from, but this is a blocker for the stable release. Looks like commit 47adc81e27d7378c00d0eda55182aeb6e66b1af1 is the culprit behind this issue.

**Note:** Once this is fixed, please write the hash of the fixing commit here, so that the issue may be marked as resolved by that commit. Even better would be to create a branch for the fix and then merge it into `main_development_branch` once the fix is complete.

**Comment by sampsapursiainen** [comment]
Corrected.

**Comment by SeSodesa** [comment]
Seems to be fixed by c8f7a1b8a75992685d2a1b1269690016c1237097.
