### ISSUE TITLE
Code style and indentations

### ISSUE THREAD

**Issue by SeSodesa** [sampsapursiainen/zeffiro_interface#217]
## Description

Most of the Matlab source files in the project currently do not follow good indentation style. Either there is no indentation at all to signify which blocks of code are within others, but we even have cases like
```matlab
    if outer_conditional_block
if inner_conditional_block
do_stuff()
end
    end
``` 
where the inner block is less indented than the outer one. This should be fixed programmatically via the function

    matlab.desktop.editor.openDocument

so that the code could be made sense of more easily. The `Document` object that the function returns contains a method `smartIndentContents`, which allows programmatic access to the smart indentation tool of Matlab.

## Steps to reproduce

1. Open almost any file in the project
2. Observe the lack of proper indentation.

## Expected behavior

The files should be properly indented, so that the code were readable.

## Context

| Name | Value |
| --- | --- |
| **Version** | f958de806 Merge pull request #193 from sampsapursiainen/192-fs2zefsh-improvements |
| **OS** | Any and all |
| **Shell** | N/A |

**Comment by mshavliuk** [comment]
I would propose not to just fix certain files of the project manually and hope that the repository will stay clean and well organized on its own, but introduce a dedicated GitHub CI action with some Matlab linter. It would block all pull requests that do not satisfy the agreed code style.

There are several linters and static code analysis tools available for MATLAB that you can use for GitHub CI (Continuous Integration) to ensure code quality and enforce best practices. Here are a few popular options:

- MATLAB Code Analyzer (M-Lint): MATLAB itself provides a built-in code analysis tool called M-Lint. It helps identify potential issues and provides suggestions to improve code quality. You can run M-Lint from the MATLAB command window or integrate it into your CI workflow using the MATLAB command-line interface.
  Link: https://blogs.mathworks.com/community/2008/09/08/let-m-lint-help-simplify-your-code/


- miss_hit: MATLAB Independent, Small & Safe, High Integrity Tools - code formatter, Style Checker, Bug finding etc
  GitHub repository: https://github.com/florianschanda/miss_hit

These tools can be integrated into your GitHub CI workflow by adding the necessary commands and configurations to your CI pipeline configuration file (e.g., .github/workflows/main.yml).

**Comment by SeSodesa** [comment]
>     * MATLAB Code Analyzer (M-Lint): MATLAB itself provides a built-in code analysis tool called M-Lint. It helps identify potential issues and provides suggestions to improve code quality. You can run M-Lint from the MATLAB command window or integrate it into your CI workflow using the MATLAB command-line interface.
>       Link: https://blogs.mathworks.com/community/2008/09/08/let-m-lint-help-simplify-your-code/

There is actually a newer linter provided by MathWorks, that has superseded `mlint`, called `checkcode`. I've been using it to check files when not using the Matlab editor, while writing code. We should probably use that in CI instead, if we choose to stick to built-in functionality.

**Comment by SeSodesa** [comment]
The pull request #218 will introduce a linting action, which will be run when things are pushed to the `main_development_branch` (although for testing purposes it is currently set to run when commits are pushed to the related feature branch). I might also add an action that will be run when a pull request is made towards `master`.

What is still missing is a comprehensive set of linter messages we wish to disallow. The list of possible values can be found at <https://se.mathworks.com/help/matlab/matlab_env/index-of-code-analyzer-checks.html>.

**Comment by SeSodesa** [comment]
There is one concern, though: we would need to be sponsored by MathWorks to use the [Matlab Actions] they provide:

> Sponsored License -- for use in support of a program or activity sponsored by MathWorks. Not for government, commercial or other non-sponsored organizational use.

@sampsapursiainen Are we considered to be spinsored by MathWorks?

[Matlab Actions]: https://github.com/matlab-actions

**Comment by SeSodesa** [comment]
Starting from R2022b, Matlab also provides the `codeIssues` function, which provides more thorough information than `mlint` and `checkcode`. Most importantly, it provides information related to issue severity, in the form of `matlab.codeanalysis.IssueSeverity.{info, warning, error}` enumeration, per each issue discovered. The linter now uses that by default, but can also call `mlint` and `checkcode` if needed.

**Comment by SeSodesa** [comment]
I wrote a little web scraper ([link]), that allowed me to generate a CSV of Matlab's linter messages and their severities. The file could be loaded as a Matlab `table`, which could be used with `mlint` and `checkcode` to block messages with a severity of `error`, as long as the CSV was loaded into the repo, preferrably into the `+utilities/` folder.

[link]: https://github.com/SeSodesa/matlab-linter-message-fetcher

**Comment by SeSodesa** [comment]
Looks like the related pull request was merged. The linter message file mentioned above was not yet added, but since most of the linter messages seem to be related to the use of `eval`, which was already in the list of unwanted warnings, I think we can close this.
