### ISSUE TITLE
Program will not start on master branch

### ISSUE THREAD

**Issue by SeSodesa** [sampsapursiainen/zeffiro_interface#55]
Hi there.

I've tried starting up ZEFFIRO Interface from the Matlab console with

	zeffiro_interface

on the `master` branch, but the program refuses to start and prints out the error message

	Error using evalin
	Unrecognized function or variable 'zef_assign_data'.

	Error in zeffiro_interface (line 34)
	evalin('base','zef_assign_data;');

Switching over to `main_development_branch` and running the same command starts the program without any issues. Shutting ZEFFIRO down, switching back to the `master` branch and then trying the command again also has it start without issues. It is then a cold start that is problematic.

The file `m/zef_assign_data.m` exists on `master`, so that is not the issue. Clearly the function symbol is then not added to the current context (or workspace) as it should be. Or maybe I am just trying to start the program in a way that is not intended?

**Comment by SeSodesa** [comment]
This diff between `master` and `main_development_branch` of the `zeffiro_interface.m` might explain the problem:
```diff
diff --git a/zeffiro_interface.m b/zeffiro_interface.m
index 281ce0d..e255ad4 100755
--- a/zeffiro_interface.m
+++ b/zeffiro_interface.m
@@ -9,7 +9,11 @@ function zeffiro_interface(varargin)
 %different operations. The list of properties (and their values) is the
 %following:
 %
-%start_mode (display/nodisplay), open_project (project file name),
+%start_mode (display/nodisplay), open_project (project file name),
+%import_segmentation (file name), import_update (file name), import_segmentation_legacy (file name),
+%import_segmentation_update_legacy (file name), save_project (file name),
+%export_fem_mesh (file name), open_figure (file name), open_figure_folder
+%(file name), run_script (file name), exit_zeffiro, quit_matlab.


 if evalin('base','exist(''zef'');')
@@ -21,6 +25,7 @@ function zeffiro_interface(varargin)
 zef_data.code_path = [zef_data.program_path filesep 'm'];
 zef_data.cluster_path =  [zef_data.program_path filesep 'cluster'];

+addpath(genpath([zef_data.program_path '/m']));
 addpath(genpath([zef_data.program_path '/mlapp']));
 addpath(genpath([zef_data.program_path '/fig']));
 addpath(genpath([zef_data.program_path zef_data.code_path]));
```
Looks like the `main_development_branch` adds the path to the folder `m/` into the `zef_data` object, which is not done on the `master` branch.

**Comment by sampsapursiainen** [comment]
Resolved.
