### ISSUE TITLE
Function lead_field_meg_fem is named as lead_field_eeg_fem

### ISSUE THREAD

**Issue by SeSodesa** [sampsapursiainen/zeffiro_interface#78]
The function in the file `m/forward_scripts/brain/lead_field_meg_fem.m` is named as `lead_field_eeg_fem`. The function should prpbably be renamed as `lead_field_meg_fem`.

<img width="589" alt="Screenshot 2022-03-17 at 16 00 33" src="https://user-images.githubusercontent.com/19917000/158841801-acf6e03f-bfb8-4408-a14c-836a3ba1dae9.png">

**Comment by sampsapursiainen** [comment]
Resolved
