### ISSUE TITLE
EIT Lead Field Error (commit b7d41a2)

### ISSUE THREAD

**Issue by SeSodesa** [sampsapursiainen/zeffiro_interface#80]
When running the script `m/forward_scripts/brain/lead_field_eit_fem.m` on the head of a certain Carsten via the *Mesh Tool*, the following error is printed in the Matlab console:

    Error using  *
    Incorrect dimensions for matrix multiplication. Check that the number of columns in the
    first matrix matches the number of rows in the second matrix. To perform elementwise
    multiplication, use '.*'.

    Error in lead_field_eit_fem (line 619)
    bg_data = Aux_mat*Current_pattern;

    Error in lead_field_matrix (line 108)
    [zef.L, zef.inv_bg_data, zef.source_positions, zef.source_directions, zef.eit_ind, zef.eit_count] = lead_field_eit_fem(zef.nodes_aux,zef.tetra,zef.sigma(:,1),zef.sensors_aux,zef.brain_ind,zef.source_ind,zef.lf_param);

    Error in zef_eit_lead_field (line 6)
    lead_field_matrix;

    Error in zef_run_forward_simulation (line 1)
    eval(zef.h_forward_simulation_table.Data{zef.forward_simulation_selected(1),3});

    Related documentation

    Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 427)
    Error while evaluating Button PrivateButtonPushedFcn.

The steps to reproduce this are as follows:

1. start Zeffiro Interface,

2. open up a project with Carsten's head,

3. select the script `zef_eit_lead_field` in the Mesh Tool, but *do not make any changes to the settings*

4. press <kbd>Run Script</kbd> in the Mesh Tool window and

5. wait for the error to appear.

This happends when the read–write `HEAD` is pointed at commit b7d41a2.

**Comment by sampsapursiainen** [comment]
Resolved
