### ISSUE TITLE
tES Lead Field Error (commit b7d41a2)

### ISSUE THREAD

**Issue by SeSodesa** [sampsapursiainen/zeffiro_interface#81]
When running the script `m/forward_scripts/brain/lead_field_tes_fem.m` via the *Mesh Tool*, the following error is printed in the Matlab console:

    Index exceeds the number of array elements. Index must not exceed 35174.

    Error in lead_field_tes_fem (line 803)
            L_tes(3*(i-1)+1,:) = L_tes(3*(i-1)+1,:)/dof_count(i);

    Error in lead_field_matrix (line 119)
    [zef.L, zef.S, zef.source_positions, zef.source_directions, zef.eit_ind, zef.eit_count] = lead_field_tes_fem(zef.nodes_aux, zef.tetra,zef.sigma(:,1),zef.sensors_aux,zef.brain_ind,zef.source_ind,zef.lf_param);

    Error in zef_tes_lead_field (line 7)
    lead_field_matrix;

    Error in zef_run_forward_simulation (line 1)
    eval(zef.h_forward_simulation_table.Data{zef.forward_simulation_selected(1),3});

    Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback (line 427)
    Error while evaluating Button PrivateButtonPushedFcn.

The steps to reproduce this are as follows:

1. start Zeffiro Interface,

2. open up a project,

3. select the script `zef_tes_lead_field` in the Mesh Tool, but *do not make any changes to the settings*

4. press <kbd>Run Script</kbd> in the Mesh Tool window and

5. wait for the error to appear.

This happends when the read–write `HEAD` is pointed at commit b7d41a2.

**Comment by sampsapursiainen** [comment]
Resolved

**Comment by sampsapursiainen** [comment]
Resolved
